autoWebServer.out
cssDirIndex.ls
directoryIndexing.h
dirIndex.ls
downloadsDirIndex.ls
iterative
iterativeDirectoryIndexing.h
iterativeDirIndexing.sh
iterativeDirIndex.ls
jsDirIndex.ls
LICENSE
main.cpp
node_modules
organized
package-lock.json
pagesDirIndex.ls
picturesDirIndex.ls
README.md
server.js
serverJS.h
setup.sh
simple
simpleDirIndex.ls
tempDirIndex.ls
